# -*- coding: utf-8 -*-
"""Visualisasi Kurs Jisdor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNKjKonptAFmbReOatV8_nyr6Ky1loUG
"""

"""
Visualisasi Kurs JISDOR — Tugas 1 NLP Project Line chart kurs USD/IDR, didesain agar gampang ditambahin overlay titik-titik berita geopolitik nantinya.

Cara pakai:
1. Pastikan 'jisdor_clean.csv' (hasil preprocess_jisdor.py) ada di working dir
2. Jalankan script ini
3. Output: 'jisdor_trend.png' (chart harian) dan tampil inline di Colab
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

df = pd.read_csv('/content/jisdor_clean.csv', parse_dates=["tanggal"])
df

# Plot line chart harian (resolusi penuh)
fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(df["tanggal"], df["kurs_jisdor"], linewidth=1, color="#1f4e79")

ax.set_title("Kurs USD/IDR (JISDOR) — September 2021 s.d. September 2026", fontsize=13)
ax.set_xlabel("Tanggal")
ax.set_ylabel("Kurs (IDR per USD)")
ax.grid(True, alpha=0.3)

# Format sumbu tanggal per 6 bulan
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("jisdor_trend.png", dpi=150)
plt.show()